### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'co_code'

### ISSUE THREAD

**Issue by elibroftw** [pyinstaller/pyinstaller#6396]
## Description of the issue
Building with pyintaller file.spec no longer works and results in the error in the title. Complete traceback at the bottom. I do believe it's a setuptools issue but I have no idea how to fix it.

This issue first started after I decided to uninstall all 3rd party modules and reinstall my project's dependencies. So that was a bad idea. I will probably end up installing Python 3.9 and rebuilding the wheels for pyinstaller and another module I need to use :(.

Maybe this isn't a bug, but I'd appreciate some brainstorming on how to fix it.

### Context information (for bug reports)
- Pyintaller versions: 5.0-dev (latest), 4.8-dev (latest), 4.7, 4.6, 4.5.1
- Python version 3.8.10 32-bit (downloaded and installed from python.org website)
- Windows 64-bit
- No solution in https://github.com/pyinstaller/pyinstaller/issues/3777 works.
  - I've tried both setuptools 49.X.Z and setuptools latest (59.3.0) with no luck
- The issue was not fixed even after uninstalling and reinstalling python
- I've run the build with `--log=DEBUG`
- `--clean` doesn't fix it either
- Works fine on my desktop which runs Python 3.10 64-bit but that's probably because I haven't uninstalled most 3rd party modules

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation (I think uninstalling Python3.8 and installing Python 3.8 counts right?)
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```py
0418 DEBUG: Scanning pkg_resources._vendor.packaging._manylinux for shared libraries or dlls
60421 DEBUG: Scanning pkg_resources._vendor.appdirs for shared libraries or dlls
60426 DEBUG: Scanning setuptools._vendor.packaging._manylinux for shared libraries or dlls
Traceback (most recent call last):
  File "C:\Users\maste\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\maste\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\maste\AppData\Local\Programs\Python\Python38-32\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\maste\AppData\Roaming\Python\Python38\site-packages\PyInstaller\__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\maste\AppData\Roaming\Python\Python38\site-packages\PyInstaller\__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\maste\AppData\Roaming\Python\Python38\site-packages\PyInstaller\building\build_main.py", line 782, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\maste\AppData\Roaming\Python\Python38\site-packages\PyInstaller\building\build_main.py", line 714, in build
    exec(code, spec_namespace)
  File "build_files\onedir.spec", line 19, in <module>
    a = Analysis([f'{os.getcwd()}/music_caster.py'],
  File "C:\Users\maste\AppData\Roaming\Python\Python38\site-packages\PyInstaller\building\build_main.py", line 277, in __init__
    self.__postinit__()
  File "C:\Users\maste\AppData\Roaming\Python\Python38\site-packages\PyInstaller\building\datastruct.py", line 155, in __postinit__
    self.assemble()
  File "C:\Users\maste\AppData\Roaming\Python\Python38\site-packages\PyInstaller\building\build_main.py", line 470, in assemble
    for (dest, source) in format_binaries_and_datas(self.graph.metadata_required()))
  File "C:\Users\maste\AppData\Roaming\Python\Python38\site-packages\PyInstaller\depend\analysis.py", line 676, in metadata_required
    out |= self._metadata_from(
  File "C:\Users\maste\AppData\Roaming\Python\Python38\site-packages\PyInstaller\depend\analysis.py", line 728, in _metadata_from
    for calls in bytecode.recursive_function_calls(code).values():
  File "C:\Users\maste\AppData\Roaming\Python\Python38\site-packages\PyInstaller\depend\bytecode.py", line 225, in recursive_function_calls
    return search_recursively(function_calls, code)
  File "C:\Users\maste\AppData\Roaming\Python\Python38\site-packages\PyInstaller\depend\bytecode.py", line 213, in search_recursively
    _memo[code] = search(code)
  File "C:\Users\maste\AppData\Roaming\Python\Python38\site-packages\PyInstaller\depend\bytecode.py", line 172, in function_calls
    for match in finditer(_call_function_bytecode, code.co_code):
AttributeError: 'NoneType' object has no attribute 'co_code'
```

**Comment by rokm** [comment]
What version of `setuptools` do you have installed? Have you tried force re-installing / upgrading `setuptools`?

The 56.0.0 that came with python 3.8.10 does not have `setuptools._vendor.packaging._manylinux` module, but the latest version (59.3.0) does...

**Comment by elibroftw** [comment]
59.3.0

**Comment by rokm** [comment]
Can you check where your `setuptools` are installed (`C:\Users\maste\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools` or `C:\Users\maste\AppData\Roaming\Python\Python38\site-packages\setuptools`), and if the installation directory happens to contain any `.pyc` or `.pyo` files *outside* of the `__pycache__` directory? If so, try removing them all (or, try removing setuptools, ensure that the installation directory is also gone, and then re-install the package).

**Comment by elibroftw** [comment]
- I removed both folders
- `pip install setuptools --force`
- `pyinstaller build_files\onedir.spec -y --log=DEBUG`

**Comment by elibroftw** [comment]
Just to clarify, this is with 4.8-dev not an older version of Pyinstaller^

**Comment by elibroftw** [comment]
Okay I fixed the above issue (removed it) by reinstalling pyinstaller but I still encounter the AttributeError.

**Comment by elibroftw** [comment]
If I add `setuptools._vendor.packaging._manylinux` to excludes, the error occurs on
`Scanning pkg_resources._vendor.appdirs for shared libraries or dlls`

**Comment by rokm** [comment]
Can you create a virtual environment and try installing pyinstaller and your program's dependencies in there? Judging by the previous intermittent error (missing `is_py2`), I'd say you have some remains of old environment lurking around your site-packages directories, and there's no way for us to debug that...

**Comment by elibroftw** [comment]
How many site-package folders are there? Just the two?

**Comment by rokm** [comment]
I think so...

**Comment by rokm** [comment]
Maybe also check what is the output of `where pyinstaller`.

**Comment by elibroftw** [comment]
I uninstalled Python, deleted **both** Python folders located in Local and Roaming.
Then I installed Python, installed the dependencies, and `--clean` ran fine. 
Thank you for informing me that there are two, not one, site-packages. Now I have a more simpler issue to deal with...

**Comment by elibroftw** [comment]
I'm going to assume installing with and without  `--user`  can mess things up.
