### ISSUE TITLE
ruamel.yaml stuff not included in archive

### ISSUE THREAD

**Issue by dantmnf** [pyinstaller/pyinstaller#5338]
## Description of the issue
ruamel.yaml stuff not included in archive.
## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.1```
* Version of Python: 3.8 and 3.9
* Platform: Windows (en-US)
* Did you also try this on another platform? No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```python
# with ruamel.yaml==0.16.12
from ruamel.yaml import YAML
print(YAML)
```

### Stacktrace / full error message

```
(venv) D:\projects\testruamel>python foo.py
<class 'ruamel.yaml.main.YAML'>

(venv) D:\projects\testruamel>dist\foo\foo.exe
Traceback (most recent call last):
  File "foo.py", line 1, in <module>
    from ruamel.yaml import YAML
ImportError: cannot import name 'YAML' from 'ruamel.yaml' (D:\projects\testruamel\dist\foo\ruamel\yaml\__init__.pyc)
[18280] Failed to execute script foo
```

`Analyis-00.toc` shows no filename for `ruamel.yaml` module:

```
...
  ('_py_abc',
   'C:\\Users\\dant\\AppData\\Local\\Programs\\Python\\Python39\\lib\\_py_abc.py',
   'PYMODULE'),
  ('ruamel.yaml', '-', 'PYMODULE'),
  ('ruamel', '-', 'PYMODULE')],
 [('_multiprocessing',
   'C:\\Users\\dant\\AppData\\Local\\Programs\\Python\\Python39\\DLLs\\_multiprocessing.pyd',
   'EXTENSION'),
...
```

**Comment by dantmnf** [comment]
import `ruamel.yaml.main` instead of `ruamel.yaml` in my program fixes this issue.

But `__init__.py` of `ruamel.yaml` already contains a `from import ruamel.yaml.main import *`. Maybe not caught by PyInstaller?

**Comment by matham** [comment]
Same issue here. `ruamel.yaml` has a pth and does some special magic, which I'm guessing broke somehow.

**Comment by matham** [comment]
According to `git bisect` https://github.com/pyinstaller/pyinstaller/commit/960ab150079b8f16fb7cfd8b1c0fe9c8da600cfa is the first bad commit.

**Comment by rokm** [comment]
> * Version of Python: 3.8 and 3.9

I can reproduce this under python 3.7 and 3.8, but not 3.9. The difference is that with older versions, `ruamel.yaml.clib` is also installed, which in turn incorrectly defines namespace packages:

In the metadata for `ruamel.yaml`, `Lib\site-packages\ruamel.yaml-0.16.12.dist-info\namespace_packages.txt` correctly contains only `ruamel`. In the metadata for `ruamel.yaml.clib`, however, `Lib\site-packages\ruamel.yaml.clib-0.2.2.dist-info\namespace_packages.txt` contains both `ruamel` and `ruamel.yaml`. 

So if `ruamel.yaml.clib` is installed, `pyinstaller` (4.1) ends up treating `ruamel.yaml` as a namespace, which leads to the error.

So it seems to me that the new behavior introduced by 960ab15 is the correct one, even though it manifests as a regression in this case. It is `ruamel.yaml.clib` that should fix their namespace definitions. 

(Removing `ruamel.yaml` from `Lib\site-packages\ruamel.yaml.clib-0.2.2.dist-info\namespace_packages.txt` should fix the issue).
