### PR TITLE
Fix django import finder to work with django < 1.7

### PR DESCRIPTION
**Pull request by mohanraj-r**
`django.setup()` was introduced in [Django 1.7](https://docs.djangoproject.com/en/1.9/releases/1.7/#standalone-scripts)
Hence the freeze process fails when freezing previous versions of django (e.g. 1.6.5)

```
6978 INFO: Loading module hook "hook-django.py"...
6982 INFO: Django root directory /mnt/xxx
Traceback (most recent call last):
  File "/tmp/freeze.1/venv/lib/python2.7/site-packages/PyInstaller/utils/hooks/subproc/django_import_finder.py", line 27, in <module
>
    django.setup()
AttributeError: 'module' object has no attribute 'setup'
7104 INFO: Collecting Django migration scripts.
```

After the fix, the freeze process works.

### CODE REVIEW

**Comment by bjones1** [comment]
PyInstaller supports only the latest version of a given package, since trying to sort through the logic of supporting older versions is too much maintenance burden. Therefore, I'm closing this request.
