### ISSUE TITLE
Execute pyinstaller binary from a executable build with pyinstaller fails with strange import error

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#858]
**Original date**: 2014/02/04
**Original reporter**: *mko0815 AND gmail DOT  COOM *

I have the following setup :
- executable build from python sources: foo.exe
- foo.exe will call another instance of foo.exe ( at a different path ) with argument "--version" to get its version info

Running "foo.exe --version" on console succeeds.
Running normal functionality of foo.exe succeeds ( the program does what is its purpose ).
Running foo.exe from within itself via subprocess.Popen fails with errors of pyinstaller functionality.
See the callstack that causes "foo.exe --version" call to fail :

```
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "D:\python\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "D:\python\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport

    exec co in mod.__dict__
  File "D:\temp\foo.py", line 17, in <module>
    from lxml import etree
ImportError: cannot import name etree
```

I was able to eliminate the problem by forcing very reduced environment variable when starting the second instance of foo.exe with the subprocess.Popen:
TMP, TEMP, PATH, SYSTEMROOT

Somehow an environment variable seems to render pyinstaller executable broken when it is run from another executable that is build with pyinstaller.

I haven't tried if the problem is present in executable build with pyinstaller 2.1.
