### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_module'

### ISSUE THREAD

**Issue by shelper** [pyinstaller/pyinstaller#2242]
Enviroment: windows 7 pro, python 3.5.2 installed with anaconda 4.2 for windows, 64bit.  pillow(PIL) version 1.1.7

I was using pyinstaller 3.2 to packup my one file python script to an .exe fie, which uses stdlib of python, with gui built on tkinter, and one 3rd party package called Pillow, the well known image lib.

I was able to pack it but got an error when running the packed .exe as: `fail to execute script pyi_rth_pkgres`

i did some research and was suggested to install the dev version on github, I did that, but then i have the following error when trying to pack up my python script, the error is copied here:

> pyinstaller.exe --onefile --windowed yuv2bmp4imager.py
> 133 INFO: PyInstaller: 3.3.dev0+b78bfe5
> 133 INFO: Python: 3.5.2
> 134 INFO: Platform: Windows-7-6.1.7601-SP1
> 138 INFO: wrote C:\Users\MPNV38\ZTools\yuv2bmp4imager.spec
> 144 INFO: UPX is not available.
> 155 INFO: Extending PYTHONPATH with paths
> ['C:\\Users\\MPNV38\\ZTools', 'C:\\Users\\MPNV38\\ZTools']
> 157 INFO: checking Analysis
> 302 INFO: checking PYZ
> 357 INFO: checking PKG
> 367 INFO: Building because toc changed
> 367 INFO: Building PKG (CArchive) out00-PKG.pkg
> Traceback (most recent call last):
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\Scripts\pyinstaller-script.py", line 11, in
> <module>
>     load_entry_point('PyInstaller==3.3.dev0+b78bfe5', 'console_scripts', 'pyinstaller')()
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\__main__.py", line 90, in run
>     run_build(pyi_config, spec_file, **vars(args))
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\__main__.py", line 46, in run_build
>     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\building\build_main.py", line 788, in main
>     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\building\build_main.py", line 734, in build
>     exec(text, spec_namespace)
>   File "<string>", line 28, in <module>
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\building\api.py", line 398, in __init__
>     strip_binaries=self.strip, upx_binaries=self.upx,
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\building\api.py", line 189, in __init__
>     self.__postinit__()
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\building\datastruct.py", line 161, in __postinit__
>     self.assemble()
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\building\api.py", line 274, in assemble
>     pylib_name=pylib_name)
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\archive\writers.py", line 332, in __init__
>     super(CArchiveWriter, self).__init__(archive_path, logical_toc)
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\archive\writers.py", line 59, in __init__
>     self._add_from_table_of_contents(logical_toc)
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\archive\writers.py", line 84, in _add_from_table_of_contents
>     self.add(toc_entry)  # The guts of the archive.
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\archive\writers.py", line 373, in add
>     code = get_code_object(nm, pathnm)
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\building\utils.py", line 571, in get_code_object
>     co = _load_code(modname, filename)
>   File "C:\Users\MPNV38\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyinstaller-3.3.dev0+b78bf
> e5-py3.5.egg\PyInstaller\building\utils.py", line 528, in _load_code
>     loader = importer.find_module(modname)
> AttributeError: 'NoneType' object has no attribute 'find_module'

I then removed the PIL dependency and use the dev version pyinstaller to pack up, everything works.

**Comment by shelper** [comment]
well, after i revised the code little bit, it worked, 
the original code has Threading and queue imported, but after i remove them , everything is fine. 
i will close this issue for now.

**Comment by elvis-epx** [comment]
I am having this issue packing a PyQt5 app in Mac, as well.

**Comment by nini122** [comment]
I was in same issue but already fixed.
- uninstall previous pyinstaller
- pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
- clone your py sources and build with new pyinstaller 4.0
that's all. good luck for all.

**Comment by breezko** [comment]
@nini122 not working on python 3.7

**Comment by AminDar** [comment]
having this problem on MAC with python 3.7

**Comment by very3b** [comment]
@nini122 not working

**Comment by mikebourbeauart** [comment]
I upgraded PyInstaller from 3.6 to 4.0 and got this error

**Comment by eddible** [comment]
I was getting this error because I had spaces in my path. I moved my script to a folder where the path didn't have any spaces and it worked.

**Comment by aykutkilic-avl** [comment]
I get this error in PyInstaller 4.10 when I write hidden_imports in multiple lines.
```
x = [...]
a=Analysis(...
   hidden_imports = x,
...)
```
solves my issue.
