### ISSUE TITLE
error when script contains Tkinter module, occurs AttributeError: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by jiangche00** [pyinstaller/pyinstaller#1877]
Hi,
    There's an error occurred when I try to use pyinstaller.
    The script tk.py is really simple:

```
#!/usr/bin/env python
import Tkinter
window = Tkinter.Tk()
window.mainloop()
```

using command:
`pyinstaller -F tk.py`
I got INFOs and ERRORs below:

```
24 INFO: PyInstaller: 3.2.dev0+7cd4c8e
24 INFO: Python: 2.7.11
25 INFO: Platform: Linux-2.6.18-371.el5-i686-with-redhat-5.10-Tikanga
25 INFO: wrote /root/tk.spec
29 INFO: UPX is not available.
30 INFO: Extending PYTHONPATH with paths
30 INFO: checking Analysis
31 INFO: Building Analysis because out00-Analysis.toc is non existent
31 INFO: Initializing module dependency graph...
33 INFO: Initializing module graph hooks...
75 INFO: running Analysis out00-Analysis.toc
124 INFO: Analyzing /root/tk.py
1556 INFO: Looking for import hooks ...
1558 INFO: Processing hook   hook-encodings.py
1979 INFO: Processing hook   hook-_tkinter.py
Traceback (most recent call last):
  File "/opt/python/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.2.dev0+7cd4c8e', 'console_scripts', 'pyinstaller')()
  File "/opt/python/lib/python2.7/site-packages/PyInstaller-3.2.dev0+7cd4c8e-py2.7.egg/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/opt/python/lib/python2.7/site-packages/PyInstaller-3.2.dev0+7cd4c8e-py2.7.egg/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/opt/python/lib/python2.7/site-packages/PyInstaller-3.2.dev0+7cd4c8e-py2.7.egg/PyInstaller/building/build_main.py", line 756, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/opt/python/lib/python2.7/site-packages/PyInstaller-3.2.dev0+7cd4c8e-py2.7.egg/PyInstaller/building/build_main.py", line 702, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/opt/python/lib/python2.7/site-packages/PyInstaller-3.2.dev0+7cd4c8e-py2.7.egg/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/opt/python/lib/python2.7/site-packages/PyInstaller-3.2.dev0+7cd4c8e-py2.7.egg/PyInstaller/building/datastruct.py", line 178, in __postinit__
    self.assemble()
  File "/opt/python/lib/python2.7/site-packages/PyInstaller-3.2.dev0+7cd4c8e-py2.7.egg/PyInstaller/building/build_main.py", line 435, in assemble
    imphook_object.update_dependencies(self.graph)
  File "/opt/python/lib/python2.7/site-packages/PyInstaller-3.2.dev0+7cd4c8e-py2.7.egg/PyInstaller/building/imphook.py", line 298, in update_dependencies
    self._process_hook_function(mod_graph)
  File "/opt/python/lib/python2.7/site-packages/PyInstaller-3.2.dev0+7cd4c8e-py2.7.egg/PyInstaller/building/imphook.py", line 192, in _process_hook_function
    self._module.hook(hook_api)
  File "/opt/python/lib/python2.7/site-packages/PyInstaller-3.2.dev0+7cd4c8e-py2.7.egg/PyInstaller/hooks/hook-_tkinter.py", line 245, in hook
    hook_api.add_datas(_collect_tcl_tk_files(hook_api))
  File "/opt/python/lib/python2.7/site-packages/PyInstaller-3.2.dev0+7cd4c8e-py2.7.egg/PyInstaller/hooks/hook-_tkinter.py", line 208, in _collect_tcl_tk_files
    tcl_root, tk_root = _find_tcl_tk(hook_api)
  File "/opt/python/lib/python2.7/site-packages/PyInstaller-3.2.dev0+7cd4c8e-py2.7.egg/PyInstaller/hooks/hook-_tkinter.py", line 159, in _find_tcl_tk
    bins = selectImports(hook_api.__file__)
  File "/opt/python/lib/python2.7/site-packages/PyInstaller-3.2.dev0+7cd4c8e-py2.7.egg/PyInstaller/depend/bindepend.py", line 489, in selectImports
    xtrapath = [os.path.dirname(pth)]
  File "/opt/python/lib/python2.7/posixpath.py", line 122, in dirname
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

```

Python is built using source code, the path is /opt/python. Tcl/Tk also built using source, path is /opt/tcltk. both of them are made using the option: --enable-shared. ld.so.conf is also added the lib path, /opt/python/lib and /opt/tcltk/lib , and the environment variable LD_LIBRARY_PATH is also set correctly.

the same code using cx_freeze is ok.

PyInstaller: 3.2.dev0+7cd4c8e
Python version: 2.7.11
Platform and version: Linux-2.6.18-371.el5-i686-with-redhat-5.10-Tikanga

**Comment by matysek** [comment]
* I tried the example and it works fine with python 2.7 on fc23.
* It looks like the hook-_tkinter.py is not able to handle custom compiled Tk.
* please look at:
  * http://www.pyinstaller.org/if-things-go-wrong.html
  * http://www.pyinstaller.org/how-to-report-bugs.html

Please provide more info with debug output.

**Comment by jiangche00** [comment]
@matysek 
Thanks, after installed tkinter, tix,  tcl-devel and tk-devel using yum installation, It's now work fine. 
but the problem why hook-_tkinter.py is not able to handle my custom-compiled Tk stiil remains......I'll try to find out some reasons that cause this problem.

**Comment by htgoebel** [comment]
Can this ticket be closed?

**Comment by Hyped-247** [comment]
I have the same problem, and for some reason the file opens for a second and closes. 
I run: pyinstaller  --onefile --windowed --hidden-import=tkinter Mo.py 
There are no errors but it doesn't open a tkinter window.
