### ISSUE TITLE
Writing to STDOUT on Windows 10 via the Windows C-API behaves differently between Python and PyInstaller

### ISSUE THREAD

**Issue by mobiusklein** [pyinstaller/pyinstaller#3178]
Python Version: 2.7.14
PyInstaller Version: 3.4.dev0+ab8fd9753 (also happens on 3.3.1)
Platform: Windows 10

Summary: After the Windows 10 Fall Creators Update, the Windows C API for writing to the console behaves slightly differently. When a script using this API from Python through `ctypes` is run in a PyInstaller EXE, the script fails while it works normally when ran normally under Python. Importing `win_unicode_console` seems to resolve this issue, but there is still a disparity between the state of the `sys.std*` streams for running under Python and running under PyInstaller. Is patching `sys.stdout` normally permitted?

Running a packaged version a script using `click` on Windows 10 after the Fall Creators Update produces an error on writing to the console, while running the script normally does not:
```
Traceback (most recent call last):
  File "C:\...\debug\pyinstaller_click\script.py", line 7, in <module>
    click.echo(u"Hello, World")
  File "C:\...\lib\site-packages\click\utils.py", line 259, in echo
    file.write(message)
  File "C:\...\lib\site-packages\click\_compat.py", line 577, in _safe_write
    return _write(s)
  File "C:\...\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\...\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\...\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\...\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\...\lib\site-packages\click\_winconsole.py", line 180, in write
    return self._text_stream.write(x)
  File "C:\...\lib\site-packages\click\_compat.py", line 63, in write
    return io.TextIOWrapper.write(self, x)
  File "C:\...\lib\site-packages\click\_winconsole.py", line 164, in write
    raise OSError(self._get_error_message(GetLastError()))
OSError: Windows error 6
[22284] Failed to execute script script
```
This appears to be related to how `click`'s `_winconsole` module attempts to use the Windows API to write text to the console, which has been reported to be causing issues since the most recent big update.

Failing Script:
```python
import sys
print(sys.stdout, sys.stderr)

import click
print(sys.stdout, sys.stderr)

click.echo(u"Hello, World")
```
Expected Output (long lines wrapped, additional empty lines):
```
(<open file '<stdout>', mode 'w' at 0x000000000518B0C0>,
 <open file '<stderr>', mode 'w' at 0x000000000518B150>)

(<open file '<stdout>', mode 'w' at 0x000000000518B0C0>,
 <open file '<stderr>', mode 'w' at 0x000000000518B150>)
Hello, World
```

If I add win_unicode_console to this script, the packaged script works, but the output is different:

```python
import sys
print(sys.stdout, sys.stderr)

import click
print(sys.stdout, sys.stderr)

import win_unicode_console
win_unicode_console.enable()
print(sys.stdout, sys.stderr)

click.echo(u"Hello, World")
```
Run under Python
```
(<open file '<stdout>', mode 'w' at 0x000000000546B0C0>,
 <open file '<stderr>', mode 'w' at 0x000000000546B150>)

(<open file '<stdout>', mode 'w' at 0x000000000546B0C0>,
 <open file '<stderr>', mode 'w' at 0x000000000546B150>)

(<win_unicode_console.streams.StrStreamWrapper name='<stdout>' encoding='utf-8'>,
 <win_unicode_console.streams.StrStreamWrapper name='<stderr>' encoding='utf-8'>)
Hello, World
```
Run under EXE
```
(<open file '<stdout>', mode 'w' at 0x000001FCC45DB0C0>,
 <open file '<stderr>', mode 'w' at 0x000001FCC45DB150>)

(<open file '<stdout>', mode 'w' at 0x000001FCC45DB0C0>,
 <open file '<stderr>', mode 'w' at 0x000001FCC45DB150>)

(<open file '<stdout>', mode 'w' at 0x000001FCC45DB0C0>,
 <open file '<stderr>', mode 'w' at 0x000001FCC45DB150>)
Hello, World
```

Note that invoking `win_unicode_console.enable()` did not patch `sys.stdout` and `sys.stderr` when ran as an EXE but the program still ran successfully. When the call to `enable` is removed but the import is retained, the program still works under EXE, which suggests there is some import-time patching going on.

Is patching `sys.stdout` and `sys.stderr` allowed? If so, why would this disparity between run-times exist?

**Comment by htgoebel** [comment]
What are `click` and `win_unicode_console`? Is `click` relevant for this issue?

> Windows 10 after the Fall Creators Update

So this does not happen before the update? Did you verify?

In PyInstaller's bootloader I can not find any special treatment for stdout and stderr. Did you check if `win_unicode_console.enable()` is testing some parameters and thus not changing sys.stdout/stderr?

**Comment by mobiusklein** [comment]
My build script worked prior to installing the Creators update, and ceased working afterwards.

`click` is a command line argument parser and console program application utility. The process by which it writes to STDOUT differing between Python and PyInstaller was the original instigator of this issue, since in theory the program should be using the same Windows APIs under Python and PyInstaller.

`win_unicode_console` is another library which patches `sys.std*` to allow Windows users to print more unicode  text to `cmd`. I noticed that when I attached the `ipdb` debugger to probe the problem parts of `click`, the problem went away, but only after its initialization code executed, which includes importing `win_unicode_console` and calling `enable`. The `enable` function checks to see if each stream `isatty()` and has a `fileno()` that matches the standard numbers (0, 1, 2) (both true), and checks that the relevant streams are "attached to consoles" by calling the the `GetConsoleMode` Windows C-API function (returns an error, resulting in skipping the stream being patched).

The function doing the checking: [GetConsoleMode](https://docs.microsoft.com/en-us/windows/console/getconsolemode). When ran under Python on STDOUT, it returns 1 (no error) and the mode bitflag was 3 (enabled for writing). When ran under PyInstaller, it returns 0 (an error) and the mode bitflag is ignored.

In pyi_pythonlib.c, stdout is made binary
https://github.com/pyinstaller/pyinstaller/blob/596c122e0fe344a17e3b88f273eada97f0aadb2a/bootloader/src/pyi_pythonlib.c#L224-L226.

So std streams are allowed to be patched under PyInstaller. It seems likely that something done on importing win_unicode_console is changing something that allows `WriteConsoleW`, the API function `click.echo` is calling that failed under normal PyInstaller behavior, to succeed.

**Comment by htgoebel** [comment]
Thanks for this analysis.

* Did you try without `click`?
* stdout is made binary **only if the option "unbuffered" is passed (which needs to be [done explicitly in the spec-file](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#giving-run-time-python-options): https://github.com/pyinstaller/pyinstaller/blob/596c122e0fe344a17e3b88f273eada97f0aadb2a/bootloader/src/pyi_pythonlib.c#L223-L226

> My build script worked prior to installing the Creators update, and ceased working afterwards.

Since PyInstaller is not touching stdout/stderr by default, and PyInstaller was not changed, and `GetConsoleMode` seems not to be changed either,  I'd call this a bug in Windows. Maybe some Windows crack has any idea ow to work-around this.

**Comment by xoviat** [comment]
Seems to work on Python 3.6 (except I receive a different error about the buffer, but it's the same when frozen as it is unfrozen). My guess is that this is fallout from using a library (python27.dll) built with a compiler (MVSC 2008) that's been unsupported for years. It's not something that I feel like debugging.

**Comment by xoviat** [comment]
Might as well post the error for the record:

```
_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
<win_unicode_console.streams.TextTranscodingWrapper name='<stdout>' encoding='utf-8'> <win_unicode_console.streams.TextTranscodingWrapper name='<stderr>' encoding='utf-8'>
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    click.echo(u"Hello, World")
  File "site-packages\click\utils.py", line 217, in echo
  File "site-packages\click\_compat.py", line 621, in func
  File "site-packages\click\_compat.py", line 385, in get_text_stdout
  File "site-packages\click\_winconsole.py", line 264, in _get_windows_console_stream
AttributeError: 'TextTranscodingWrapper' object has no attribute 'buffer'
[11152] Failed to execute script test
```

**Comment by mobiusklein** [comment]
win_unicode_console isn't needed under Py3.6. I'm able to run my tiny test script without issue after freezing it. The Windows C-API call succeeds under the frozen executable when using 3.6 instead of 2.7. 

Unfortunately, the larger application I'm packaging can't be updated to run under Py3 for a variety of reasons, including my poor understanding of the increased complication of shipping the UCRT for non-Win10 machines with PyInstaller. I can use win_unicode_console as a workaround for Py2.7 for now, though I wish I understood the reason why it worked. Hopefully I put enough keywords into the issue report that other people hitting this problem can find it.

**Comment by xoviat** [comment]
UCRT is not a problem. Just download [one of these files](https://anaconda.org/conda-forge/vs2015_runtime/files) and dump the DLLs into your application folder.

**Comment by davidt99** [comment]
After some investigating, I can add that this is happening only in 64bit python (2.7), in 32bit it works fine.
This issue is probably related to #2902.

**Comment by zebra-lucky** [comment]
After investigation in Process Explorer i've found a cause of problems:
Hi-entropy ASLR enabled by default. It's possible to disable per
high-entropy per app via "Windows Defender Security Center".

![aslr-high-entropy](https://user-images.githubusercontent.com/992125/41790843-8b147eca-765c-11e8-8a0e-efc72c19624d.png)

**Comment by htgoebel** [comment]
Thanks for the analysis. Just to be sure: You have analyzed the original issue:
> related to how click's _winconsole module attempts to use the Windows API

What is your suggested solution? Provide tome information  the Wiki or the manual? Change build options fr the bootloader? Drop Windows support?

**Comment by zebra-lucky** [comment]
The problem arised with click 6.7. Details of problem is use of `ctypes` with `kernel32.WriteConsoleW`. It returns with error 6 (Invalid handle), and handle is get by `kernel32.GetStdHandle`.

Temporary workaround is switch off `Don't use high entropy` for Bottom-up ASLR.
I'm need to do more investigations for other recipes.

**Comment by zebra-lucky** [comment]
After tests with click I try to do same on simple app with `ctypes`, and testing PyInstaller build and also run script from python on same platform. Only difference in the Process Explorer found was `high-entropy`.

**Comment by zebra-lucky** [comment]
More screens to clarify the problem (current version of trezorctl from python-trezor package uses click):

Process Explorer properties of errored process:

![error6_run](https://user-images.githubusercontent.com/992125/42034296-479fb53e-7ae8-11e8-806f-21aa593c3dc5.png)

Windows Defender settings of errored process (same as without customization):

![error6_settings](https://user-images.githubusercontent.com/992125/42034297-47cee49e-7ae8-11e8-96a3-954a92b24752.png)

Process Explorer properties of normally running process:

![ok_run](https://user-images.githubusercontent.com/992125/42034298-47f28c64-7ae8-11e8-8180-14a250006b38.png)

Windows Defender settings of normally running process:

![ok_setttings](https://user-images.githubusercontent.com/992125/42034299-4814f43e-7ae8-11e8-8e07-671fbdd6669b.png)

Seems a checkbox "Don't use hight entropy" have wrong label (in opposition what Process Explorer shows).

This is on Windows 10 64-bit "Fall Creators Update" version, but same error raised on previous "Creators Update" version.

**Comment by zebra-lucky** [comment]
So, to finalize, `python.exe` do not have "High-Entropy", when run on same platform without changes to Window Defender per process policy. Python is build with MS Visual C++ as far as I know, and there is a optional flags to generate binaries with ASLR support.

**Comment by Legorooj** [comment]
I'm closing this. Python 2.7 is not longer supported; therefore it's no longer a problem
