### ISSUE TITLE
Strange build error under Ubuntu with latest python3 revision

### ISSUE THREAD

**Issue by pandel** [pyinstaller/pyinstaller#1306]
Hi!

With the current python3 git revision, I get a strange error when trying to build a package under Ubuntu 15.04.vivid:

    22 INFO: UPX is not available.
    27 INFO: Extending PYTHONPATH with /home/holger/Pythonprojects/opsiPackageBuilder
    34 INFO: checking Analysis
    38 INFO: Building because out00-Analysis.toc missing or bad
    46 INFO: Creating base_library.zip for Python 3
    2708 INFO: running Analysis out00-Analysis.toc
    2738 INFO: Analyzing opsipackagebuilder.py
    5848 INFO: Analyzing /usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/loader/_pyi_bootstrap.py
    6332 INFO: Analyzing /usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/loader/pyi_importers.py
    6350 INFO: Analyzing /usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/loader/pyi_archive.py
    6368 INFO: Analyzing /usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/loader/pyi_carchive.py
    6390 INFO: Analyzing /usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/loader/pyi_os_path.py
    6400 INFO: Analyzing hidden import 'sip'
    6406 ERROR: Hidden import 'sip' not found
    6412 INFO: Hidden import 'PyQt5.QtPrintSupport' has been found otherwise
    6417 INFO: Analyzing hidden import 'PyQt5.QtSql'
    6423 INFO: Hidden import 'codecs' has been found otherwise
    6430 INFO: Hidden import 'encodings' has been found otherwise
    6434 INFO: Looking for import hooks ...
    6447 INFO: Processing hook   hook-encodings.py
    6757 INFO: Processing hook   hook-pydoc.py
    6766 INFO: Processing hook   hook-sysconfig.py
    6771 INFO: Processing hook   hook-distutils.py
    6782 INFO: Processing hook   hook-xml.py
    6787 INFO: Processing hook   hook-site.py
    6798 INFO: Processing hook   hook-xml.sax.py
    6802 INFO: Processing hook   hook-xml.dom.domreg.py
    6807 INFO: Processing hook   hook-xml.dom.py
    6819 INFO: Analyzing run-time hooks ...
    6837 INFO: Looking for dynamic libraries
    6999 INFO: Looking for eggs - TODO
    7028 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython3.4m.so.1.0
    7033 INFO: Adding Python library to binary dependencies
    Traceback (most recent call last):
      File "/usr/local/bin/pyinstaller", line 9, in <module>
        load_entry_point('PyInstaller===3.0dev-156df37', 'console_scripts', 'pyinstaller')()
      File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/main.py", line 88, in run
        run_build(opts, spec_file, pyi_config)
      File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/main.py", line 46, in run_build
        PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
      File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/build.py", line 2127, in main
        build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
      File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/build.py", line 2071, in build
        exec(compile(open(spec).read(), spec, 'exec'))
      File "pyinstaller-linux.spec", line 6, in <module>
    runtime_hooks=None)
      File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/build.py", line 406, in __init__
        self.__postinit__()
      File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/build.py", line 242, in __postinit__
        self.assemble()
      File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/build.py", line 816, in assemble
        importer_names = self.graph.importer_names(n)
      File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/depend/analysis.py", line 184, in importer_names
        return [importer.identifier for importer in iter_inc]
      File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.0dev_156df37-py3.4.egg/PyInstaller/depend/analysis.py", line 184, in <listcomp>
        return [importer.identifier for importer in iter_inc]
    AttributeError: 'NoneType' object has no attribute 'identifier'

I didn't try to build this distribution package for a while now, so I cannot really say, when the error was introduced, but as it has worked already (some pyinstaller commits ago) with the current spec file I am not really sure where to start searching for i. e. an errorneous or missing file.

BTW, under Windows, everything is building fine with the same revision!

Regards,
Holger

**Comment by htgoebel** [comment]
Please help us tracking this down. If you know approximately which revision "some pyinstaller commits ago" worked, you can use `git bisect` for finding the one causing the error. Using `git bisect` is easy and quick. Thanks.

**Comment by pandel** [comment]
;-)) nothing to bisect here! Just when I wanted to start inspecting the code after a last git pull, everything worked fine now. I don't know why, but your commit e944769deea8b0f04b555499c1413a8a5ead7495 did the trick!

Perfect! Many thanks!

**Comment by pandel** [comment]
Arg! Happening again... So here is what I did in detail before:

- checked out commit 3429bfbb7d3d3080a403a6f5fdaf1620c0dfb758 and installed it via setup.py
- run pyinstaller in my project, everything fine
- check out python3 branch HEAD, removed /usr/local/bin/python3.4/dist_packages/PyInstaller-... folder and re-installed it via setup.py
- run pyinstaller in my project WITHOUT deleting build and dist directory before, worked

Now I cleaned dist and build and tried to run pyinstaller again, and boom! error again...

I'll try to find out what happened...

**Comment by htgoebel** [comment]
Please try running PyInstaller from the checked out directory and bisect here. Please mind to remote /usr/local/bin/python3.4/dist_packages/PyInstaller-...

**Comment by pandel** [comment]
So... My bad! I'm working in a virtual machine on this, so I did a snapshot reset to start with a alleged clean state. What I didn't noticed was that the snapshot somehow didn't contain any necessary debian package for my distribution.

... I'm very sorry to have opened this request!
