### ISSUE TITLE
AttributeError: 'super' object has no attribute '_safe_import_module'

### ISSUE THREAD

**Issue by improve100** [pyinstaller/pyinstaller#8346]
pyinstaller -F launch.py
260 INFO: PyInstaller: 6.4.0, contrib hooks: 2024.2
260 INFO: Python: 3.8.10
266 INFO: Platform: Linux-5.13.0-52-generic-x86_64-with-glibc2.29
266 INFO: wrote launch.spec
269 INFO: Extending PYTHONPATH with paths
['/home/scripts/tools']
469 INFO: checking Analysis
469 INFO: Building Analysis because Analysis-00.toc is non existent
469 INFO: Initializing module dependency graph...
470 INFO: Caching module graph hooks...
477 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "/home/.local/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 228, in _console_script_run
    run()
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 212, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 69, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 1091, in main
    build(specfile, distpath, workpath, clean_build)
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 1031, in build
    exec(code, spec_namespace)
  File "/home/codes/autonomous_driving/src/system/scripts/ms_tools/mslaunch.spec", line 4, in <module>
    a = Analysis(
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 470, in __init__
    self.__postinit__()
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 550, in assemble
    self.graph = initialize_modgraph(excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/depend/analysis.py", line 927, in initialize_modgraph
    graph = PyiModuleGraph(
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/depend/analysis.py", line 108, in __init__
    self._analyze_base_modules()
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/depend/analysis.py", line 257, in _analyze_base_modules
    self._base_modules = [mod for req in required_mods for mod in self.import_hook(req)]
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/depend/analysis.py", line 257, in <listcomp>
    self._base_modules = [mod for req in required_mods for mod in self.import_hook(req)]
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1232, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1411, in _find_head_package
    target_package = self._safe_import_module(
  File "/home/.local/lib/python3.8/site-packages/PyInstaller/depend/analysis.py", line 484, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
AttributeError: 'super' object has no attribute '_safe_import_module'

**Comment by rokm** [comment]
What linux distribution is this, and how did you install python?

**Comment by improve100** [comment]
ubuntu2004  comes with Python 3.9

**Comment by bwoodsend** [comment]
>  File "/home/.local/lib/python3.8/site-packages/PyInstaller/depend/analysis.py", line 108, in init

You are not using 3.9

**Comment by improve100** [comment]
Sorry to say wrong, it is Python3.8.10 comes with ubuntu2004

**Comment by bwoodsend** [comment]
Well `print("hello")` works in a minimal `ubuntu:20.04` docker container so unless you give us a minimal reproducer [like the issue template asks for](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) then we can't help you.

**Comment by rokm** [comment]
> Well `print("hello")` works in a minimal `ubuntu:20.04` docker container so unless you give us a minimal reproducer [like the issue template asks for](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) then we can't help you.

I don't think reproducer would help here, unless it was instructions on how to exactly replicate that system setup.

Because the issue seems to be that `PyInstaller.depend.PyiModuleGraph.analysis._safe_import_module` fails to resolve superclass method here:

https://github.com/pyinstaller/pyinstaller/blob/90256f93ed943daf6de53c7dd39710a415f705cb/PyInstaller/depend/analysis.py#L484

which should be available in parent ModuleGraph:

https://github.com/pyinstaller/pyinstaller/blob/7aea3993f79c9bb6ec1e4faf8cc4ac3ec10292ab/PyInstaller/lib/modulegraph/modulegraph.py#L1723-L1724

I cannot reproduce this either, and I'm not sure how that could even happen.

---

So perhaps, @improve100, can you try adding a 

```
print("superclass:", super())
print("dir(supercalss):", dir(supper()))
```

before

https://github.com/pyinstaller/pyinstaller/blob/90256f93ed943daf6de53c7dd39710a415f705cb/PyInstaller/depend/analysis.py#L484

Maybe that will shed some light on what is going on...

**Comment by improve100** [comment]
I suspect it has to do with my pip version. Whenever I upgrade pip, issues arise. I uninstalled pip completely and then reinstalled that specific version   pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

surprisingly it worked.

**Comment by rokm** [comment]
You should avoid installing packages via pip in your system's site-packages (dist-packages) or user's site, as it might interfere with system software that's written in python (and depends on python packages that were installed via apt, and which pip-install might have overwrite). Instead, create a virtual environment using python's `venv` module, and use that for PyInstaller (and if you ever need a combination of system-installed packages with some pip-installed packages over them, use `--system-site-packages` when creating virtual environment using `venv`).

**Comment by improve100** [comment]
Thank you very much for your answer. I will trying to use Python in a virtual environment.
