### ISSUE TITLE
PyInstaller 3.2: ImportError that doesn't exist in PyInstaller 2.1

### ISSUE THREAD

**Issue by pegazbre** [pyinstaller/pyinstaller#2005]
Few days ago we switched from Python 2.7 x86 to Python 2.7 x64 and from PyInstaller 2.1 to PyInstaller 3.2.

We didn't change the PyInstaller build script (.spec file) and with the new version build process finished without errors. But when we start our frozen app we got ImportError that didn't exist in previous version of PyInstaller. So we rolled back to older PyIntaller version and repeat build procedure and this time frozen app worked as expected.

Because of complexity of our app and whole build procedure I will try to explain in simplified manner what we actually do during build procedure.

For example we have two modules moduleA.py and moduleB.py organized in Python packages:

![capture](https://cloud.githubusercontent.com/assets/19586473/15567556/5ecbe734-2327-11e6-90b5-fcbd56220ef7.PNG)

We don't want PyInstaller to collect these modules and put them in frozen .exe so during build procedure (and inside .spec file) we removed them from dependency list with this line of code:

```
tocList = [(packageName,'','') for packageName options.cyton_setup.to_remove]
a.pure = a.pure - TOC(tocList)
```
After PyInstaller build process is finished, we manually 'Cythonize' required modules using Cython and appropriate 64bit compiler (Microsoft Visual C++ Compiler Package for Python 2.7). Then we put whole python package structure in the root folder where frozen .exe (and all collected dependencies - we use One Dir option) are located:

![capture2](https://cloud.githubusercontent.com/assets/19586473/15567617/9a27958a-2327-11e6-8c94-23136630815b.PNG)

In frozen app built by PyInstaller 2.1 this worked because app didn't find required libraries in frozen .exe but instead it found them in its root directory. In case of frozen app built with PyInstaller 3.2 this doesn't work anymore.

We have tried to put original files instead of Cythonized Python extensions but without luck, app cannot find them.

Our simplified .spec file looks like:

```
# -*- mode: python -*-
import os
import sys
from PyInstaller.building.api import PYZ, EXE, COLLECT
from PyInstaller.building.build_main import Analysis
from PyInstaller.building.datastruct import TOC

# append current directory
sys.path.append(os.getcwd())
from config import options

a = Analysis(['main.py'],
                hiddenimports=['numpy', 'pylab', 'scipy.io.matlab.streams', 'sip','jinja2.ext',
                            'scipy.special._ufuncs_cxx'],
                excludes = ['_gtkagg', '_tkagg', 'bsddb', 'curses', 'pywin.debugger',
                         'pywin.debugger.dbgcon', 'pywin.dialogs', 'tcl','Tkconstants', 'Tkinter', 
                         'wx' ,'PyQt4.QtOpenGL','PyQt4.QtSql','PyQt4.QtXml','PyQt4.QtTest'],
                hookspath=None,
                runtime_hooks=None)

# remove our source from dependencies list
tocList = [(packageName,'','') for packageName in options.cyton_setup.to_remove]
a.pure = a.pure - TOC(tocList)

pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='frozen_app.exe',
          debug=False,
          strip=None,
          upx=True,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=None,
               upx=True,
               name='frozen_app')
```

We know that if we put Python extensions in form:
`packages.package1.moduleA.pyd`

in the root directory it will work but we need to keep old structure, and we don't want to have multiple copies of Python extension files.

Is there some changes in new PyInstaller 3.2 that we need to be aware? Did somebody have similar problems?

**Comment by codewarrior0** [comment]
A quick test showed me that this functionality is still present in v3.2. I placed a package containing a extension module and a pure-python module into the app's root directory and was able to import both of them. Can you provide the ImportError you get when you run your app?

**Comment by pegazbre** [comment]
ImportError is connected to one of Extension modules that are created afterwards PyInstaller finished its job and copied to root folder of frozen app. If I put fully qualified named extension of that module in the root that first ImportError are gone but i got next one (for the next module) until I put all extension in the root (with correctly fully qualified name). 

If have written simple python script that imports those modules and put it in root folder to test can those modules organized in packages can be imported and it worked correctly.

All of this worked in case of PyInstaller 2.1 and we didn't change anything besides compiler needed for Cython.

**Comment by pegazbre** [comment]
Small correction . In the .spec file I had changed import statements because those used for PyInstaller 2.1 didn't work for new version. That is a only thing we changed that is connected to PyInstaller.

**Comment by pegazbre** [comment]
I'm thinking...In PyInstaller 3.2 is enough to remove modules from dependency list with: 
`a.pure = a.pure - TOC(tocList)`
and manually add them to root folder in order to be found by frozen app or they also should be removed from somewhere else?

**Comment by htgoebel** [comment]
So you basically say: the Cythonized module is in file `.\package1\moduleA.pyd` bute reuqires to be named `.\package1.moduleA.pyd`. Correct?

**Comment by pegazbre** [comment]
Yes cythonized module should be in `.\package1\moduleA.pyd` and I got message in form:
`ImportError: cannot import name 'name of the module'`. if I put `package1.moduleA.pyd` in the root then it works. For some reason frozen app doesn't find `.\package1\moduleA.pyd` module only `.\package1.moduleA.pyd`

Of course if I don't remove anything from dependency list it will work correctly because it will find frozen module .pyc file inside exe and it won't look further.

Also I have tried the same build procedure with the Python 2.7.11 x86, PyInstaller 3.2 on the other machine, without luck.

**Comment by pegazbre** [comment]
Ok. I have created fully automated build setup (in order to help you and myself) of above mentioned hypothetical example. All you need is to run **run.bat** and _**my_app**_ frozen app will be created in _dist_ directory.
 If you start my-app.exe from the command prompt you will get ImportError, regardless module exists in python packages structure that is also in the root. But if you copy files from **copy_content_to_root** folder (fully qualified named python extensions) to the frozen app root it will work.

To run this build setup you will need:

1. Windows (I have Windows 10 x64)
2. Python 2.7.x x64 (I have Python 2.7.11 x64)
3. Microsoft Visual C++ Compiler for Python from http://www.microsoft.com/en-us/download/details.aspx?id=44266
4. Dependecies from _requirements.txt_ (PyInstaller==3.2, Paver==1.2.4, Cython==0.24)

Build example: [example.zip](https://github.com/pyinstaller/pyinstaller/files/289740/example.zip)

**Comment by codewarrior0** [comment]
Your build scripts are not using PyInstaller correctly.

You are copying Python source files into the frozen app's folder and then cythonizing them there. Instead, what you should do is cythonize them in place before running PyInstaller. This way, PyInstaller will find the .pyd files and prefer to use them over the .py files, which means the .pyd files will be bundled with the correct filenames and the .py files will not be included.

**Comment by pegazbre** [comment]
I am aware that we could setup build procedure on this way (we tried that when we used PyInstaller 2.1). If we first cytonize required modules (and remove .py files after .pyd is created) and then start PyInstaller build process, PyInstaller will collect and put them in the root folder with fully qualified name and it will work. 

But, we need to have the whole Python package structure in the root directory because of our API (API cannot find moduleA if it is named like _.\package1.moduleA.pyd_ and located in root) and in that case we will have multiple of the same extension modules (one in python package structure and one in the root).

The main question remains: why app built with the PyInstaller 2.1 can find required modules in the python packages structure and app built with the PyInstaller 3.1 cannot? Like I said we didn't changed anything besides version of PyInstaller and we expected that everything will work.

In documentation for PyInstaller 3.2 I have found:

> This is the resolution order of import statements in a bundled app:
> 
> 1. Is it a built-in module? A list of built-in modules is in variable sys.builtin_module_names.
> 2. Is it a module embedded in the executable? Then load it from embedded archive.
> 3. Is it a C-extension? The app will try to find a file with name package.subpackage.module.pyd or package.subpackage.module.so
> 4. **Next examine paths in the sys.path. There could be any additional location with python modules or .egg filenames.**
> 5. If the module was not found then raise ImportError.

So frozen app didn't find required module in the archive neither appropriate extension in the root but it should find additional modules in the sys.path (sys.path points to the root directory).
I also noticed that in PyInstaller 2.1 uses PYTHONPATH and PYTHONHOME instead of sys.path to set library search path. Maybe is that key difference.

**Comment by codewarrior0** [comment]
>So frozen app didn't find required module in the archive neither appropriate extension in the root but it should find additional modules in the sys.path (sys.path points to the root directory).

I tested this a few days ago.The functionality you are asking for is still present. The frozen app will import modules, both pure-python and extensions, from the root directory if they are not found otherwise. It worked for me in a simple example, so I'm not sure why it doesn't work for you. Try adding the verbose option to your EXE build step:

```
exe = EXE(pyz,
          [('v', '', 'OPTION')],
          a.scripts,
# ...
```

This will make the frozen app output a bunch of debugging info about the module searching whenever a module is imported. Maybe that will have some clue.

**Comment by pegazbre** [comment]
Here what I got when put this Verbose option in the same example that I have posted few posts ago:

```
PyInstaller Bootloader 3.x
LOADER: executable is D:\PROJECT\test_project\dist\my_app\my_app.exe
LOADER: homepath is D:\PROJECT\test_project\dist\my_app
LOADER: _MEIPASS2 is NULL
LOADER: archivename is D:\PROJECT\test_project\dist\my_app\my_app.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(D:\PROJECT\test_project\dist\my_app)
LOADER: Already in the child - running user's code.
LOADER: Python library: D:\PROJECT\test_project\dist\my_app\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is D:\PROJECT\TEST_P~1\dist\my_app
LOADER: Setting runtime options
LOADER: Runtime option: v
LOADER: Initializing python
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is D:\PROJECT\test_project\dist\my_app
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
import marshal # builtin
LOADER: extracted struct
LOADER: callfunction returned...
import _struct # builtin
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
import nt # builtin
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
import zlib # builtin
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
import imp # builtin
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
# PyInstaller: FrozenImporter(D:\PROJECT\TEST_P~1\dist\my_app\my_app.exe?150241)
import os # PyInstaller PYZ
import errno # builtin
import ntpath # PyInstaller PYZ
import stat # PyInstaller PYZ
import genericpath # PyInstaller PYZ
import warnings # PyInstaller PYZ
import linecache # PyInstaller PYZ
import types # PyInstaller PYZ
import UserDict # PyInstaller PYZ
import _abcoll # PyInstaller PYZ
import abc # PyInstaller PYZ
import _weakrefset # PyInstaller PYZ
import _weakref # builtin
import copy_reg # PyInstaller PYZ
import encodings # PyInstaller PYZ
# encodings.codecs not found in PYZ
import encodings # PyInstaller PYZ
# encodings.codecs not found in PYZ
import codecs # PyInstaller PYZ
import _codecs # builtin
# encodings.encodings not found in PYZ
# encodings.encodings not found in PYZ
import encodings.aliases # PyInstaller PYZ
# encodings.__builtin__ not found in PYZ
# encodings.__builtin__ not found in PYZ
# ctypes not found in PYZ
LOADER: Running main.py
import packages # PyInstaller PYZ
import packages.package1 # PyInstaller PYZ
# packages.package1.moduleA not found in PYZ
import packages.package1 # PyInstaller PYZ
# packages.package1.moduleA not found in PYZ
Traceback (most recent call last):
  File "main.py", line 1, in <module>
ImportError: cannot import name moduleA
Failed to execute script main
LOADER: OK.
LOADER: Cleaning up Python interpreter.
# clear __builtin__._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.exitfunc
# clear sys.exc_type
# clear sys.exc_value
# clear sys.exc_traceback
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup __main__
# cleanup[1] encodings
# cleanup[1] _weakrefset
# cleanup[1] abc
# cleanup[1] nt
# cleanup[1] _warnings
# cleanup[1] zipimport
# cleanup[1] codecs
# cleanup[1] packages
# cleanup[1] _struct
# cleanup[1] signal
# cleanup[1] _codecs
# cleanup[1] encodings.aliases
# cleanup[1] _weakref
# cleanup[1] exceptions
# cleanup[1] packages.package1
# cleanup[2] copy_reg
# cleanup[2] pyimod01_os_path
# cleanup[2] os.path
# cleanup[2] struct
# cleanup[2] pyimod03_importers
# cleanup[2] errno
# cleanup[2] warnings
# cleanup[2] imp
# cleanup[2] pyimod02_archive
# cleanup[2] ntpath
# cleanup[2] UserDict
# cleanup[2] genericpath
# cleanup[2] stat
# cleanup[2] _abcoll
# cleanup[2] types
# cleanup[2] zlib
# cleanup[2] linecache
# cleanup[2] os
# cleanup[2] marshal
# cleanup sys
# cleanup __builtin__
# cleanup ints: 20 unfreed ints
# cleanup floats
```

> I tested this a few days ago.The functionality you are asking for is still present. The frozen app will import modules, both pure-python and extensions, from the root directory if they are not found otherwise. It worked for me in a simple example, so I'm not sure why it doesn't work for you.

Did you try with my example or your own? Did you remove modules from PyInstaller dependency list  and then manually put required modules in the root (only in the root or inside some python packages similar like in my case)?

**Comment by codewarrior0** [comment]
Found out what's causing this. In [`pyimod03_importers`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/loader/pyimod03_importers.py#L669), we add our FrozenImporter to both `sys.meta_path` and `sys.path_hooks`. The former is the usual way the importer is used, but the latter was added for compatibility with `pkgutil.get_loader` (for reasons I can't recall). The `sys.path_hooks` entry is what is blocking the import system from falling back to the standard importer which imports from the filesystem. [According to PEP 302:](https://www.python.org/dev/peps/pep-0302/#specification-part-2-registering-hooks)

> Note that if the callable returns an importer object for a specific sys.path entry, the builtin import machinery will not be invoked to handle that entry any longer, even if the importer object later fails to find a specific module.

What happens in this case is first the importer on `sys.meta_path` is asked to find the module `packages.package1` via `find_module`. It does so and returns itself as the loader, which is then called to load the module via `load_module`. Then it is asked to load `packages.package1.moduleA`, which it cannot find, so it returns None for the loader, causing the PEP 302 system to fall back. PEP 302 runs through all the `sys.meta_path` entries, none of them find the module, so it again falls back to `sys.path_hooks`.

Oddly, when it gets to the importer in `sys.path_hooks`, it first asks it *again* to find the module `packages.package1` via calling the importer object, *even though this module was already loaded via `sys.meta_path`!* After it returns the `sys.path_hooks` loader for that package, it will never fall back to the filesystem again, as it says in the PEP 302 quote above. So when this loader fails to load `packages.package1.moduleA`, the PEP 302 system stops there and gives you the ImportError you see.

What you can do about it is remove the package files e.g. `c:\example\packages\package1\__init__.py` from `a.pure`. Those files being in the PYZ is what is causing the `sys.path_hooks` importer to return a loader for that package, which stops the filesystem from being searched.

**Comment by pegazbre** [comment]
I'm glad that you found what is the problem :) 
I think that quick fix is only applicable for this simple example but in our real build scenario it will be bit problematic, because in on package are located not only modules that need to be kicked out from frozen app (and provided as cytonized extension in app root) but also modules that should be located in PYZ archive.
I assume that you will make some sort modification in PyInstaller  _pyimod03_importers_ to handle correctly this case.

**Comment by codewarrior0** [comment]
I'm not sure we can fix this without removing the `pkg_util.get_loader` compatibility. Don't hold your breath for any changes.

> but also modules that should be located in PYZ archive.

You have kind of a weird use-case, since you have some kind of plugin API that completely ignores Python's import system and searches the filesystem for modules on its own. If you need a package to be visible to both the PyInstaller-hooked Python import system and your own API's system, you need to kick that entire package and all of the packages that contain it out of the PYZ archive. Having the package half-in and half-out of the archive is what's causing this problem.

**Comment by pegazbre** [comment]
Actually entire API is outside PYZ archive  (it is not called anywhere in the code so it won't be collected as dependency and frozen inside PYZ archive) but sharable modules are both in PYZ archive and outside organized in appropriate python packages (and some of them are cythonized). 

All that user need to do is either to extend PATH variable with our app root path and add PYTHONPATH variable that point to the same directory or to dynamically from the code extend sys.path. 
On this way all modules (cythonized or pure) organized in python structure outside of frozen app will become available in user own Python environment.

**Comment by pegazbre** [comment]
> I'm not sure we can fix this without removing the pkgutil.get_loader compatibility. Don't hold your breath for any changes.

So we can say that this functionality (falling back to the standard importer which imports from the filesystem) won't exists anymore in PyInstaller 3.2 becouse in PyInstaller 2.1 was working ok?

**Comment by codewarrior0** [comment]
> So we can say that this functionality (falling back to the standard importer which imports from the filesystem) won't exists anymore in PyInstaller 3.2 becouse in PyInstaller 2.1 was working ok?

This functionality still exists. Just make sure your packages are either fully inside the PYZ or fully outside of it. The way you have it, the packages `__init__` files are still in the PYZ and that's what is throwing you off. Yes, this is a regression from v2.1, but it's not likely to be fixed.

**Comment by pegazbre** [comment]
As we don't want to rollback to PyInstaller 2.1 and we cannot remove everything from archive we are going to use approach where we first cythonize required modules and then let PyInstaller to collect them because that is the best solution for time being.

Thank you for your support.

**Comment by pegazbre** [comment]
Well I have encountered one problem with approach to first cythonize required module and then start PyInstaller build. 
In case module that need to be cythonized (for example _moduleA_) has import to some other module (lets called it _moduleX_)  and that module imports other modules. If we cythonize _moduleA_ and start PyInstaller build, PyInstaller won't be able to analyze cythonized extension for imports and required _moduleX_ won't be collected (and all other modules that it imports).

I now remember that we had similar problem with this approach when we first tried it with PyInstaller 2.1 so we change strategy to first let PyInstaller collect all dependencies, remove from dependency list modules that need to be cythonized and then cythonize those modules and manually put them to the root.

**Comment by tallforasmurf** [comment]
So this would only occur if *moduleX* is a pure-Python module imported only by *moduleA* (or only by cython-ated modules). The cython-ization effectively conceals the import statement.

That would make *moduleX* literally a hidden import. So add it to the spec file as a hidden import. Then it and its dependencies are included.

Note there is no penalty for naming a module as hidden even if it is not hidden; it does not get included redundantly or anything (a TOC behaves as a set). So there would be no problem if *moduleA* was not cython-ified before bundling.

**Comment by htgoebel** [comment]
Another solution could be to integrate the Cythonozation-step into the spec-file. Then walk the file-tree looking for `.pyd` files, and them to `a.binaries` and remove the corresponding source file from `a.pure`. (This may require some more tweaking, of course.)

As codewarrior already wrote: it's not likely to be fixed.
