### ISSUE TITLE
MacOS: App does not start anymore with GLib 2.88

### ISSUE THREAD

**Issue by lovetox** [pyinstaller/pyinstaller#9410]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.19.0```
* Version of Python: 3.13
* Platform: OS X
* How you installed Python: brew
* Did you also try this on another platform? Does it work there? Dont use other Platform

### A minimal example program which shows the error

```
from gi.repository import GLib
```

### Stacktrace / full error message

```
% /Applications/Gajim.app/Contents/MacOS/launch
Traceback (most recent call last):
  File "gi/overrides/__init__.py", line 159, in load_overrides
  File "gi/overrides/__init__.py", line 36, in __getattr__
  File "gi/module.py", line 123, in __getattr__
AttributeError: 'gi.repository.GLib' object has no attribute 'unix_signal_add_full'

```

The error is a bit mysterious, but i traced it down to pygobject being not able to import the new GLib platform module GLibUnix-2.0.

This worked fine with GLib 2.86.4, but broke when we switched to GLib 2.88.0.

I checked the hooks and it seems the hooks recompile gir files and change some paths. Note that GLibUnix is never imported in the application, its implicitly loaded when you import GLib, so pyinstaller probably has no idea that this module is needed.

**Comment by rokm** [comment]
> Note that GLibUnix is never imported in the application, its implicitly loaded when you import GLib, so pyinstaller probably has no idea that this module is needed.

Indeed. We'll need to add a hidden import in `GLib` hook (and add hooks for `GLibUnix`). This particular issue seems to arise with combination of GLib 2.88.0 and PyGObject >= 3.56.

But I've noticed that a similar implicit import happens for `GioUnix` when `Gio` is imported (with older GLib and PyGObject versions, too); in contrast to above, this one does not seem to be fatal per-se - but if we do not collect `GioUnix`, it ends up being opportunistically loaded from Homebrew environment, which is a recipe for disaster...

**Comment by lovetox** [comment]
And just to note, its not of particular interest to me, but there was also a platform module for windows, GLibWin32
