### ISSUE TITLE
Pyinstaller and pypylon

### ISSUE THREAD

**Issue by HuguesMar** [pyinstaller/pyinstaller#8243]
Hello, 

I have a problem for a pypylon program with libraries. I want to create a .exe program but I have this error.
ImportError: cannot import name '_pylon' from 'pypylon' 

Output of pyinstaller --version: V6.3.0
Pypylon Version : V3.0.1
Version of Python: V3.11.7
Platform: Windows 11

It works with Python V3.11.7, Pyinstaller V6.0.0 and pypylon V2.3.0

Do you have any idea ? It is a library bug ?

Thanks

**Comment by rokm** [comment]
It is likely a PyInstaller regression - see https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/689.

**Comment by HuguesMar** [comment]
OK Thanks a lot
